### ISSUE TITLE
Handle authorization cancelling

### ISSUE THREAD

**Issue by lukaville** [odnoklassniki/ok-android-sdk#14]
How handle authorization cancel event? `OkListener` callback allows to handle only `onError` and `onSuccess` events. But when user cancels authorization (e.g. taps back button), SDK fires onError callback (with `Авторизация была отменена` error message).

**Comment by lintax** [comment]
We have not separated CANCEL and FAIL scenarios since do not think that there is a valuable difference for the requesting application.

However, for now you can fork the SDK, change code executed in [back scenario](https://github.com/odnoklassniki/ok-android-sdk/blob/master/odnoklassniki-android-sdk/src/main/java/ru/ok/android/sdk/OkAuthActivity.java#L86).

We are also accepting patches, so you are free to offer a pull request. However, bear in mind, that since most applications do not need to distinguish cancel and error scenarios, the API changes should not cause any changes for them in their code.
